### ISSUE TITLE
Large embedded <image>s are disappears.

### ISSUE THREAD

**Issue by linushp** [LLK/scratch-svg-renderer#100]
you can see the svg file : 
https://wscdn.xiaoma.cn/db/ef/ce/dbefcee9284998c31464e130517f4fe2.svg

I use the "scratch-gui"  project  and create many costome use the svg file and make them random moving 。。

When I use iphone (ios) safari browser to see the  works before  .  

The image in the svg can not display .

**Comment by linushp** [comment]
https://m-world.xiaomawang.com/main/project/crSM666J

**Comment by towerofnix** [comment]
Potentially related to #58.

**Comment by linushp** [comment]
> Potentially related to #58.

it is not the #58 

my issue is noly in player .

**Comment by linushp** [comment]
I have known the reason .   

`         
   const img = new Image();
            img.onload = () => {
                this._cachedImage = img;
                this._drawFromImage(scale, onFinish);
            };
`

at iOS platform , when 'img.onload' occured , the bitmap in the svg file has not loaded . 

so we defer some  time .

**Comment by Cryptorcheck** [comment]
> I have known the reason .
> 
> ` const img = new Image(); img.onload = () => { this._cachedImage = img; this._drawFromImage(scale, onFinish); };`
> 
> at iOS platform , when 'img.onload' occured , the bitmap in the svg file has not loaded .
> 
> so we defer some time .

Please tell me how to fix it
