### ISSUE TITLE
Why does the bitmap adapter resize in two passes?

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-svg-renderer#122]
Currently, the bitmap adapter resizes images in two steps: first resizing horizontally then resizing vertically.

[The comment](https://github.com/LLK/scratch-svg-renderer/blob/develop/src/bitmap-adapter.js#L18) says that this is done in order to preserve nearest-neighbor sampling, but [nearest-neighbor sampling appears to work even if images are resized in one pass](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled#Result).

Is there a certain browser that requires two passes, or is there something else I'm missing?

**Comment by fsih** [comment]
I vaguely remember it being firefox on windows? Maybe it isn't true anymore!

**Comment by adroitwhiz** [comment]
I think I finally figured this out-- [`imageSmoothingEnabled` only takes effect when scaling an image *up*](https://bugzilla.mozilla.org/show_bug.cgi?id=1360415) and linear interpolation is always used when scaling an image *down*, so this *may* be a hack to get nearest-neighbor interpolation when scaling an image down.
