### ISSUE TITLE
Improve performance of image resizing

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-svg-renderer#13]
### Expected Behavior

Bitmap image import (and resizing) should be as fast as possible!

### Actual Behavior

Image resizing is slow for large images.

![image](https://user-images.githubusercontent.com/1786240/39136473-5064c980-46e9-11e8-8931-e345053cdaab.png)

### Steps to Reproduce

Load really large images as costumes or backdrops.

#### Notes
See discussion in comments in #12

**Comment by fsih** [comment]
I think this data is from back when we were using jimp, so it's not relevant anymore
