### ISSUE TITLE
"Scratch 2.0 Coping Strategies"?

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-svg-renderer#14]
This is a cute repository title (LLK/scratch-2.0-coping-strategies), but it's not entirely descriptive.. I think scratch-2.0-svg-coping-strategies (or even scratch-svg-coping-strategies) would be more obvious? This sounds more like a repository of PDFs and resources for teachers who are worried that migrating their class to using Scratch 2.0 (from Scratch 1.4) might be a bit bumpy :)

Edit: Otherwise, it should definitely be noted that the README needs to be updated. I don't know about NPM; I'd guess that there's already a scratch-svg-renderer package published, and I'm not sure how/if you plan to rename that.

**Comment by fsih** [comment]
@kchadha was thinking of removing importBitmap, in which case we would revert the name.

**Comment by towerofnix** [comment]
@fsih Got it. Thanks for the info!
