### ISSUE TITLE
Crash when rendering thin images on Firefox on fullscreen

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-svg-renderer#170]
### Expected Behavior
SVG renderer doesn't crash

### Actual Behavior
It crashes. This is probably caused by images that are thin: i.e. 0 < width < 1

### Steps to Reproduce
Project 432397436, on fullscreen mode.

### Operating System and Browser
Firefox 81.0.1, Windows 10

[original report](https://scratch.mit.edu/discuss/post/4473003/) by gray_turtle: Firefox Nightly 83.0a1 on Linux, cannot repro on Chrome

Note: I think the root cause is similar to LLK/scratch-gui#5972

**Comment by fsih** [comment]
Repro project: https://scratch.mit.edu/projects/432397436/fullscreen/
