### ISSUE TITLE
Split up the SvgRenderer monolith

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-svg-renderer#211]
### Expected Behavior

SVG renderer functionality should be exported in a granular way, so each place that depends on it can take only what it needs (e.g. 2.0 -> 3.0 SVG conversion, measuring SVGs, deserializing SVGs, actually drawing SVGs). This is blocking https://github.com/LLK/scratch-render/pull/594.

### Actual Behavior

Currently there's lots of functionality mixed into `SvgRenderer`, some of which is used in `scratch-render`, some of which is used in `scratch-vm`, etc. This should all be separated out, especially since https://github.com/LLK/scratch-svg-renderer/pull/127 will be adding lots of `scratch-render`-specific SVG rendering code, and it would be cleaner for that to be able to live in `scratch-render`.

**Comment by fsih** [comment]
This looks like a really good improvement! It could also be a really helpful step towards some of our other SVG issues. I'm going to talk to our tech lead about it to make sure it's ok, and then we'll start looking at putting this in.
