### ISSUE TITLE
Why fix the STAGE_WIDTH and STAGE_HEIGHT in src/bitmap-adapter.js

### ISSUE THREAD

**Issue by OumCc** [LLK/scratch-svg-renderer#330]
Very confused

Why fix the STAGE_WIDTH and STAGE_HEIGHT in [src/bitmap-adapter.js](https://github.com/LLK/scratch-svg-renderer/blob/develop/src/bitmap-adapter.js) in getResizedWidthHeight function

![image](https://user-images.githubusercontent.com/10840542/158921086-0102aa17-f620-46fc-9b85-9c0239b7b455.png)

if I change the stage size in gui, there seems to be something wrong

[gui layout-constants.js](https://github.com/LLK/scratch-gui/blob/develop/src/lib/layout-constants.js)

![image](https://user-images.githubusercontent.com/10840542/158921339-0fe4eb4a-7359-4f14-88d9-05a147447fb1.png)

**Comment by kchadha** [comment]
This is not a user facing bug and low priority tech debt so closing until it becomes an issue.
