### ISSUE TITLE
"Names consisting only of numbers are not supported" error

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-svg-renderer#53]
`<g id="1" transform="translate(46.000000, 37.000000)" fill-rule="nonzero">`
SVGs with IDs consisting of only numbers can't be imported, such as one with the above substring.
That seems quite brittle. By default some vector applications and SVG optimizers give groups a number.
from @thisandagain

---
Moved from LLK/paper.js#13
/cc @fsih @thisandagain @rschamp @gnarf

**Comment by thisandagain** [comment]
@mzgoddard I'd like to add this to the "compatibility" project.

**Comment by thisandagain** [comment]
Related to https://github.com/LLK/scratch-gui/issues/3534

**Comment by BryceLTaylor** [comment]
I'm seeing this issue when opening the paint editor on the sprite "Thumbnail" in this project: https://scratch.mit.edu/projects/153085197/editor/

**Comment by apple502j** [comment]
Repro: https://scratch.mit.edu/discuss/post/3894342/
Sprite: Instructions
