### ISSUE TITLE
svgs from inkscape fail to load because of bad svg:text tags

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-svg-renderer#95]
### Expected Behavior

All svgs that loaded in Scratch 2 should load in Scratch 3.

### Actual Behavior

Some SVGs that were made in inkscape don't appear in the project and are instead replaced by a question mark.  

In this project, https://scratch.mit.edu/projects/320461517 (original is https://scratch.mit.edu/projects/167167477 that I copied in case it gets fixed), there is a sprite called "platformer" that is a large svg that doesn't load in Scratch 3 but does in Scratch 2.  

I downloaded the sprite and repeatedly modified the svg until it was able to be uploaded.  What did it was removing all of the <svg:text> tags.

The tags say:
`<svg:text aaa:space="preserve" style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:40px;line-height:125%;font-family:'Ryuker BRK';-inkscape-font-specification:'Ryuker BRK';letter-spacing:0px;word-spacing:0px;fill:#800000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" x="445.00635" y="562.65411" id="text3387" sodipodi:linespacing="125%" xmlns:aaa="http://www.w3.org/XML/1998/namespace">
        <svg:tspan sodipodi:role="line" id="tspan3389" x="445.00635" y="562.65411">Red is bad</svg:tspan>
      </svg:text>`

`<svg:text aaa:space="preserve" style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:40px;line-height:125%;font-family:'Phorfeit Slant BRK';-inkscape-font-specification:'Phorfeit Slant BRK';letter-spacing:0px;word-spacing:0px;fill:#806600;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1;" x="1755.4688" y="932.83093" id="text3441" sodipodi:linespacing="125%" xmlns:aaa="http://www.w3.org/XML/1998/namespace">
        <svg:tspan sodipodi:role="line" id="tspan3443" x="1755.4688" y="932.83093">Go ^</svg:tspan>
      </svg:text>`

 `<svg:text aaa:space="preserve" style="font-style:normal;font-weight:normal;font-size:40px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#806600;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" x="1559.125" y="684.39343" id="text3445" sodipodi:linespacing="125%" xmlns:aaa="http://www.w3.org/XML/1998/namespace">
        <svg:tspan sodipodi:role="line" id="tspan3447" x="1559.125" y="684.39343">
          <svg:tspan style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-family:'Phorfeit Slant BRK';-inkscape-font-specification:'Phorfeit Slant BRK';fill:#806600" id="tspan3449">Go &gt;</svg:tspan>
        </svg:tspan>
      </svg:text>`

Here is the original (0.svg) that can't be uploaded and the modified version of the svg (0modified2.svg) that can:
[inkscapeSVGTextTag.zip](https://github.com/LLK/scratch-svg-renderer/files/3378377/inkscapeSVGTextTag.zip)

### Steps to Reproduce

Load the project above
Note: the "platformer" (ground) doesn't appear
load the project in scratch 2
Note: the ground appears
Download the "platformer" sprite from scratch 2
Upload 0.svg into another project
Note: it doesn't appear.  Instead you get a question mark
Open 0.svg in a text editor and delete all oft he svg:text tags and their contents
Save and upload the modified version of 0.svg into a 3.0 project
Note: the sprite appears

### Operating System and Browser

Mac Chrome

**Comment by adroitwhiz** [comment]
This happened for a costume in one of my projects. IIRC the issue is specifically the `aaa:space` attribute on the text tag.

EDIT: Repro SVG:
```
<?xml version="1.0" encoding="UTF-8"?>
<svg version="1.1" viewBox="0 0 68 68" xmlns="http://www.w3.org/2000/svg">
    <rect aaa:space="preserve" x="2" y="2" width="64" height="64" fill="white" stroke="black" stroke-width="4" xmlns:aaa="http://www.w3.org/XML/1998/namespace"/>
</svg>
```

See [the XML 1.1 namespace spec](https://www.w3.org/TR/xml-names11/#ns-decl):

"The prefix xml is by definition bound to the namespace name http://www.w3.org/XML/1998/namespace. It MAY, but need not, be declared, and MUST NOT be undeclared or bound to any other namespace name. __Other prefixes MUST NOT be bound to this namespace name__, and it MUST NOT be declared as the default namespace. "

**Comment by fsih** [comment]
@BryceLTaylor This change should be ready for QA now

**Comment by BryceLTaylor** [comment]
This change seems to fix it on Safari but not on Chrome.  It also caused some strange behavior when downloading and re-uploading the original project.  We are going to revert the change for now.

**Comment by fsih** [comment]
@BryceLTaylor this is ready to be re-QAed

**Comment by fsih** [comment]
@BryceLTaylor this is ready for testing on https://llk.github.io/scratch-gui/develop/ , for the third time
